/**
 * Canonical API error codes for the Sprint 33 stabilization path.
 *
 * Keep these codes stable and machine-readable. User-facing copy can evolve,
 * but clients, tests, logs, and analytics should rely on these identifiers.
 */

export const API_ERROR_CODES = {
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  AUTH_FORBIDDEN: "AUTH_FORBIDDEN",
  AUTH_INVALID_CALLBACK_ORIGIN: "AUTH_INVALID_CALLBACK_ORIGIN",
  AUTH_SESSION_REQUIRED: "AUTH_SESSION_REQUIRED",

  SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
  SESSION_NOT_OWNED: "SESSION_NOT_OWNED",
  SESSION_INVALID_STATE: "SESSION_INVALID_STATE",
  SESSION_ADVANCE_CONFLICT: "SESSION_ADVANCE_CONFLICT",
  SESSION_TERMINAL: "SESSION_TERMINAL",

  TUTOR_RATE_LIMITED: "TUTOR_RATE_LIMITED",
  TUTOR_CONTEXT_UNAVAILABLE: "TUTOR_CONTEXT_UNAVAILABLE",
  TUTOR_SOURCE_INSUFFICIENT: "TUTOR_SOURCE_INSUFFICIENT",
  TUTOR_TURN_FAILED: "TUTOR_TURN_FAILED",

  CONTENT_INVALID: "CONTENT_INVALID",
  CONTENT_UPLOAD_FAILED: "CONTENT_UPLOAD_FAILED",
  CONTENT_PAYLOAD_TOO_LARGE: "CONTENT_PAYLOAD_TOO_LARGE",
  CONTENT_RATE_LIMITED: "CONTENT_RATE_LIMITED",

  VALIDATION_INVALID_JSON: "VALIDATION_INVALID_JSON",
  VALIDATION_INVALID_QUERY: "VALIDATION_INVALID_QUERY",
  VALIDATION_INVALID_BODY: "VALIDATION_INVALID_BODY",

  RATE_LIMITED: "RATE_LIMITED",
  REQUEST_TIMEOUT: "REQUEST_TIMEOUT",
  REQUEST_ID_INVALID: "REQUEST_ID_INVALID",

  INTERNAL_UNEXPECTED: "INTERNAL_UNEXPECTED",
  INTERNAL_DEPENDENCY_FAILED: "INTERNAL_DEPENDENCY_FAILED",
  INTERNAL_DATABASE_ERROR: "INTERNAL_DATABASE_ERROR",
} as const;

export type ApiErrorCode = (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];

export const API_ERROR_DOMAINS = {
  AUTH: "AUTH",
  SESSION: "SESSION",
  TUTOR: "TUTOR",
  CONTENT: "CONTENT",
  VALIDATION: "VALIDATION",
  RATE_LIMIT: "RATE_LIMIT",
  INTERNAL: "INTERNAL",
} as const;

export type ApiErrorDomain = (typeof API_ERROR_DOMAINS)[keyof typeof API_ERROR_DOMAINS];

export function getApiErrorDomain(code: ApiErrorCode): ApiErrorDomain {
  if (code.startsWith("AUTH_")) return API_ERROR_DOMAINS.AUTH;
  if (code.startsWith("SESSION_")) return API_ERROR_DOMAINS.SESSION;
  if (code.startsWith("TUTOR_")) return API_ERROR_DOMAINS.TUTOR;
  if (code.startsWith("CONTENT_")) return API_ERROR_DOMAINS.CONTENT;
  if (code.startsWith("VALIDATION_")) return API_ERROR_DOMAINS.VALIDATION;
  if (code === API_ERROR_CODES.RATE_LIMITED) return API_ERROR_DOMAINS.RATE_LIMIT;
  return API_ERROR_DOMAINS.INTERNAL;
}
